FROM clamav/clamav:1.5.4_base-debian13-slim@sha256:bbefacdc028635d83f4e6c81abf94db4f1d859b6f6009d90c94ae3d22625b235

USER root

RUN apt-get update \
    && apt-get upgrade -y \
    && rm -rf /var/lib/apt/lists/* \
    && sed -i 's/^#StreamMaxLength .*/StreamMaxLength 100M/' /etc/clamav/clamd.conf \
    && sed -i 's/^#MaxScanSize .*/MaxScanSize 500M/' /etc/clamav/clamd.conf

USER clamav

ENTRYPOINT ["/init-unprivileged"]

HEALTHCHECK --interval=30s --timeout=5s --start-period=120s --retries=10 \
    CMD /usr/local/bin/clamdcheck.sh
